nanoseconds(x::Clock) = value(x)
microseconds(x::Clock) = fld(value(x), NANOSECONDS_PER_MICROSECOND)
milliseconds(x::Clock) = fld(value(x), NANOSECONDS_PER_MILLISECOND)
seconds(x::Clock) = fld(value(x), NANOSECONDS_PER_SECOND)
minutes(x::Clock) = fld(value(x), NANOSECONDS_PER_MINUTE)
hours(x::Clock) = fld(value(x), NANOSECONDS_PER_HOUR)
days(x::Clock) = fld(value(x), NANOSECONDS_PER_DAY)
weeks(x::Clock) = fld(value(x), NANOSECONDS_PER_WEEK)

Nanoseconds(x::Clock) = Nanosecond(nanoseconds(x))
Microseconds(x::Clock) = Microsecond(microseconds(x))
Milliseconds(x::Clock) = Millisecond(milliseconds(x))
Seconds(x::Clock) = Second(seconds(x))
Minutes(x::Clock) = Minute(minutes(x))
Hours(x::Clock) = Hour(hours(x))
Days(x::Clock) = Day(days(x))
Weeks(x::Clock) = Week(weeks(x))

nanosecond(x::Clock) = mod(nanoseconds(x), NANOSECONDS_PER_MICROSECOND)
microsecond(x::Clock) = mod(microseconds(x), MICROSECONDS_PER_MILLISECOND)
millisecond(x::Clock) = mod(milliseconds(x), MILLISECONDS_PER_SECOND)
second(x::Clock) = mod(seconds(x), SECONDS_PER_MINUTE)
minute(x::Clock) = mod(minutes(x), MINUTES_PER_HOUR)
hour(x::Clock) = mod(hours(x), HOURS_PER_DAY)
day(x::Clock) = days(x)
week(x::Clock) = weeks(x)

Nanosecond(x::Clock) = Nanosecond(nanosecond(x))
Microsecond(x::Clock) = Microsecond(microsecond(x))
Millisecond(x::Clock) = Millisecond(millisecond(x))
Second(x::Clock) = Second(second(x))
Minute(x::Clock) = Minute(minute(x))
Hour(x::Clock) = Hour(hour(x))
Day(x::Clock) = Day(day(x))
Week(x::Clock) = Week(week(x))
