nanoseconds(x::Span) = value(x)
microseconds(x::Span) = fld(value(x), NANOSECONDS_PER_MICROSECOND)
milliseconds(x::Span) = fld(value(x), NANOSECONDS_PER_MILLISECOND)
seconds(x::Span) = fld(value(x), NANOSECONDS_PER_SECOND)
minutes(x::Span) = fld(value(x), NANOSECONDS_PER_MINUTE)
hours(x::Span) = fld(value(x), NANOSECONDS_PER_HOUR)
days(x::Span) = fld(value(x), NANOSECONDS_PER_DAY)
weeks(x::Span) = fld(value(x), NANOSECONDS_PER_WEEK)

Nanoseconds(x::Span) = Nanosecond(nanoseconds(x))
Microseconds(x::Span) = Microsecond(microseconds(x))
Milliseconds(x::Span) = Millisecond(milliseconds(x))
Seconds(x::Span) = Second(seconds(x))
Minutes(x::Span) = Minute(minutes(x))
Hours(x::Span) = Hour(hours(x))
Days(x::Span) = Day(days(x))
Weeks(x::Span) = Week(weeks(x))

nanosecond(x::Span) = mod(nanoseconds(x), NANOSECONDS_PER_MICROSECOND)
microsecond(x::Span) = mod(microseconds(x), MICROSECONDS_PER_MILLISECOND)
millisecond(x::Span) = mod(milliseconds(x), MILLISECONDS_PER_SECOND)
second(x::Span) = mod(seconds(x), SECONDS_PER_MINUTE)
minute(x::Span) = mod(minutes(x), MINUTES_PER_HOUR)
hour(x::Span) = mod(hours(x), HOURS_PER_DAY)
day(x::Span) = days(x)
week(x::Span) = weeks(x)

Nanosecond(x::Span) = Nanosecond(nanosecond(x))
Microsecond(x::Span) = Microsecond(microsecond(x))
Millisecond(x::Span) = Millisecond(millisecond(x))
Second(x::Span) = Second(second(x))
Minute(x::Span) = Minute(minute(x))
Hour(x::Span) = Hour(hour(x))
Day(x::Span) = Day(day(x))
Week(x::Span) = Week(week(x))

Nanoseconds(x::IntSpan) = Span(Nanosecond(x))
Microseconds(x::IntSpan) = Span(Microsecond(x))
Milliseconds(x::IntSpan) = Span(Millisecond(x))
Seconds(x::IntSpan) = Span(Second(x))
Minutes(x::IntSpan) = Span(Minute(x))
Hours(x::IntSpan) = Span(Hour(x))
Days(x::IntSpan) = Span(Day(x))
Weeks(x::IntSpan) = Span(Week(x))
